### ISSUE TITLE
Please consider changing the license from GPLv2-only to GPLv2 or any later version

### ISSUE THREAD

**Issue by dacmot** [DS-Minetest/helicopter#1]
Following a pending change by Pavel, https://github.com/SokolovPavel/helicopter/issues/11, would you please consider changing the licensing terms accordingly?

**Comment by Desour** [comment]
IIRC, when I rewrote this mod, only trivial code of Pavel was left. So I can probably just drop his license all together.
I still haven't chosen a license for my code though. (I will probably choose something like Apache or MIT.)

**Comment by dacmot** [comment]
I'm not a lawyer, so take my opinion with a grain of salt. That being said, I would question the legality of changing the license of a derivative work. In the case where you have to maintain the license of the original work, you would need to wait for Pavel to change it first.

About using the [Apache License](https://www.gnu.org/licenses/license-list.en.html#apache2) from the GPL v2

>Please note that this license is not compatible with GPL version 2, because it has some requirements that are not in that GPL version. These include certain patent termination and indemnification provisions. The patent termination provision is a good thing, which is why we recommend the Apache 2.0 license for substantial programs over other lax permissive licenses.

And be careful about using the [Expat license](https://www.gnu.org/licenses/license-list.en.html#Expat):

> Some people call this license “the MIT License,” but that term is misleading, since MIT has used many licenses for software. It is also ambiguous, since the same people also call the [X11 license](https://www.gnu.org/licenses/license-list.en.html#X11License) “the MIT License,” failing to distinguish them. We recommend not using the term “MIT License.”

**Comment by dacmot** [comment]
Upon further research, going [from GPL to Apache](https://www.apache.org/licenses/GPL-compatibility.html) doesn't seem possible for derivative work. The question still remains: is it derivative work?

For copyright purposes, there's something called a [clean room design](https://en.wikipedia.org/wiki/Clean_room_design) that could allow you to claim full copyright of the mod. I don't know if it would be possible to claim that, given that the repository was explicitly forked.

At this point, for a hobby project such as a minetest mod, it might just be simpler to just ask Pavel to re-license to something more permission than GPL.

I hope any of this is useful...

**Comment by Desour** [comment]
> For copyright purposes, there's something called a [clean room design](https://en.wikipedia.org/wiki/Clean_room_design) that could allow you to claim full copyright of the mod. I don't know if it would be possible to claim that, given that the repository was explicitly forked.

IIRC, I haven't looked much into the code of the old mod (it was too broken anyway). I've just reimplemented it. But I haven't started from scratch, which makes things harder now for copyright.

> At this point, for a hobby project such as a minetest mod, it might just be simpler to just ask Pavel to re-license to something more permission than GPL.

I agree. However, Pavel isn't active anymore, afaik. 
I've also asked him to license his media, but there is still no answer after 3 years: https://github.com/SokolovPavel/helicopter/issues/8 (The whynot helicopter fork still uses all of that media.)

**Comment by Lazerbeak12345** [comment]
In upstream, Pavel just changed license from GPLv2-only to GPLv2-or-later

**Comment by Lazerbeak12345** [comment]
Forgot to mention, licences were also added to the images.

**Comment by dacmot** [comment]
@Desour, just checking if you're still alive ;) As Lazerbeak mentioned, Pavel updated the licenses with https://github.com/SokolovPavel/helicopter/pull/12 and https://github.com/SokolovPavel/helicopter/pull/15. I've updated my PR #2 to reflect it as well.

The only thing left after that would be for you to decide on the derivative license. Easiest would be GPLv2 or later as discussed previously.

**Comment by Desour** [comment]
Thanks for reminding me!

I've merged your PR, and then made the licensing more clear. The repo is using REUSE now. :)

**Comment by Lazerbeak12345** [comment]
I'm not familiar with REUSE. Is there a resource I could learn about this?

**Comment by dacmot** [comment]
https://reuse.software/tutorial

-------- Message d'origine --------
